<?php
function nexersys_landing_permission() {
  return array(
    'access nexersystv' => array(
      'title' => t('Access Nexersystv'),
      'description' => t('Basic access to site for anons'),
      'restrict access' => FALSE,
    ),
  );
}

/**
* Implementation of hook_menu()
*/

function nexersys_landing_menu(){
    $items['admin/nexersys-form'] = array(
    'title' => 'Landing page control',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('access nexersystv'),
    'page arguments' => array('campaign_landing_form'),      
  );

return $items;

}
function nexersys_landing_field_formatter_info(){

}
function _camp_types(){
    $options = array(0=>'Unknown', 1=>'Commercial', 2=>'Home', 3=>'Pro',);
    return $options;
}
function nexersys_landing_init(){
}
/**
 * Implements hook_theme().
 */
function nexersys_landing_theme() {
    $theme = array(
        'nexersys_landing_view' => array(
            'render element' => 'nexersys_landing',
            //'path' => drupal_get_path('module', 'nexersys_landing') . '/templates',
            //'template' => 'nexersys-landing-form',
            //'variables' => array('form' => NULL,),
            ),
    );
    return $theme;
}
/**
 * Implements hook_node_view().
 */
function nexersys_landing_node_view($node, $view_mode) {
    print '<pre style="font-size:11px;color:green;">';
    print_r($node);
    print '</pre>';
    $variables = array();
$form = drupal_get_form('campaign_landing_form');
    
    // Add the output to the node.
    $node->content['nexersys_landing'] = array(
        '#theme' => 'nexersys_landing_view',
        //'#node' => $node,
        //'#teaser' => $teaser,
        //'#page' => $page,
        '#form' => $form,
  );
}
function theme_nexersys_landing_view($variables){
    
    return drupal_render($variables['nexersys_landing']['#form']);

}

function nexersys_landing_preprocess_node(&$vars){
    
    //debug($vars);
}

function campaign_landing_form($variables){
    $form['#prefix'] = '<div id="nex_request">    <div class="left">
        <div class="left-top">
            <div><img src="/sites/all/themes/nexersystv/form/img/nex-bro-home.png"/></div>
        </div>
        <div class="left-bottom">
            <div><img src="/sites/all/themes/nexersystv/form/img/nex-form-bot-left.png"/></div>
        </div>
    </div>
    <div class="right"><table>';
    $form['#method'] = 'post';
    $form['#action'] = 'https://crm.zoho.com/crm/WebToLeadForm';
    $form['LEADCF13'] = array(
        '#type' => 'hidden',
        '#value' => 'NexersysNow.com Ebrochure Form',
    );
    $form['LEADCF14'] = array(
        '#type' => 'hidden',
        '#value' => 'http://nexersysNow.com/ebrochure',
    );
    $form['LEADCF1'] = array(
        '#type' => 'hidden',
        '#value' => 'NexersysNow.com Ebrochure Form',
    );
    $form['LEADCF5'] = array(
        '#type' => 'hidden',
        '#value' => 'http://nexersysNow.com/ebrochure',
    );
    $form['First Name'] = array(
        '#prefix' => t('<tr><td>Phone Number</td><td>'),
        '#type' => 'textfield', 
        '#title' => 'First Name',
        '#required' => true,
        '#attributes' => array('class' => array('nexersys validate[required]'),),
        '#title_display' => 'invisible',
        '#suffix' => t('</td></tr>'),
    );
    $form['Last Name'] = array(
        '#prefix' => t('<tr><td>Phone Number</td><td>'),
        '#type' => 'textfield', 
        '#title' => 'Last Name',
        '#required' => true,
        '#attributes' => array('class' => array('nexersys validate[required]'),),
        '#title_display' => 'invisible',
        '#suffix' => t('</td></tr>'),
    );
    $form['Phone'] = array(
        '#prefix' => t('<tr><td>Phone Number</td><td>'),
        '#type' => 'textfield', 
        '#title' => 'Phone Number',
        '#required' => true,
        '#attributes' => array('class' => array('nexersys validate[required]'),),
        '#title_display' => 'invisible',
        '#suffix' => t('</td></tr>'),
    );
    $form['submit'] = array(
                '#prefix' => t('<tr><td></td><td>'),

        '#type' => 'image_button',
        '#src' => drupal_get_path('module', 'nexersys_landing') . '/img/request-but-up.png',
                '#suffix' => t('</td></tr>'),

        
    );
    $form['#suffix'] = '</table></div></div>';
    return $form;
}

function nexersys_landing_preprocess_page(&$vars){
    drupal_add_css(drupal_get_path('module', 'nexersys_landing') . '/css/validationEngine.jquery.css');
    drupal_add_css(drupal_get_path('module', 'nexersys_landing') . '/css/nex_request.css');
    drupal_add_js(drupal_get_path('module', 'nexersys_landing') . '/js/jquery.validationEngine-en.js');
    drupal_add_js(drupal_get_path('module', 'nexersys_landing') . '/js/jquery.validationEngine.js');
    drupal_add_js(drupal_get_path('module', 'nexersys_landing') . '/js/campaign_landing.js');
}