<?php
function nexersys_landing_permission() {
  return array(
    'access nexersystv' => array(
      'title' => t('Access Nexersystv'),
      'description' => t('Basic access to site for anons'),
      'restrict access' => FALSE,
    ),
  );
}

/**
* Implementation of hook_menu()
*/

function nexersys_landing_menu(){
    $items['admin/nexersys-form'] = array(
    'title' => 'Landing page control',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('access nexersystv'),
    'page arguments' => array('campaign_landing_form'),
  );

return $items;

}
function nexersys_landing_field_formatter_info(){

}
function _camp_types(){
    $options = array('Unknown'=>'unknown', 'Commercial'=>'commercial', 'Home'=>'home', 'Pro'=>'pro',);
    return $options;
}
function nexersys_landing_init(){
}
/**
 * Implements hook_theme().
 */
function nexersys_landing_theme() {
    $theme = array(
        'nexersys_landing_view' => array(
            'render element' => 'nexersys_landing',
            //'path' => drupal_get_path('module', 'nexersys_landing') . '/templates',
            //'template' => 'nexersys-landing-form',
            //'variables' => array('form' => NULL,),
            ),
    );
    return $theme;
}
//$postdata = $_POST;
//debug($postdata);
/**
 * Implements hook_node_view().
 */
function nexersys_landing_node_view($node, $view_mode) {
    global $base_url;
    drupal_add_css(drupal_get_path('module', 'nexersys_landing') . '/css/validationEngine.jquery.css');
    drupal_add_css(drupal_get_path('module', 'nexersys_landing') . '/css/nex_request.css');
    drupal_add_js(drupal_get_path('module', 'nexersys_landing') . '/js/jquery.validationEngine-en.js');
    drupal_add_js(drupal_get_path('module', 'nexersys_landing') . '/js/jquery.validationEngine.js');
    drupal_add_js(drupal_get_path('module', 'nexersys_landing') . '/js/campaign_landing.js');
    $item = menu_get_item();    
    $path = $item['href'];
    $path = drupal_get_path_alias($path);
    $vars = array(
        'camp_form_url' => $base_url . '/' . $path,
        'camp_name' => $node->title,
        'camp_src' => $node->field_camp_src[$node->language][0]['value'],
        'camp_thank_url' => $node->field_camp_thank_url[$node->language][0]['value'],
        'camp_type' => $node->field_camp_type[$node->language][0]['value'],
        'camp_phone' => $node->field_camp_phone[$node->language][0]['value'],
        'camp_offer_txt' => $node->field_camp_offer_txt[$node->language][0]['value'],
        'camp_media' => $node->field_camp_media[$node->language][0]['value'],
        'camp_term' => $node->field_camp_term[$node->language][0]['value'],
        'camp_thank_url' => $node->field_camp_thank_url[$node->language][0]['value'],

    );
    $form = drupal_get_form('campaign_landing_form', $vars);

    // Add the output to the node.
    $node->content['nexersys_landing'] = array(
        '#theme' => 'nexersys_landing_view',
        //'#node' => $node,
        //'#teaser' => $teaser,
        //'#page' => $page,
        '#form' => $form,
  );
}
function theme_nexersys_landing_view($variables){
    return drupal_render($variables['nexersys_landing']['#form']);
}

function nexersys_landing_form_alter(&$form, &$form_state, $form_id){
    global $base_url;
    if($form_id == 'campaign_node_form'){
        $form['field_camp_website']['und'][0]['value']['#default_value'] = $base_url;
        $form['field_camp_website']['und'][0]['value']['#attributes']['class'][] = 'utm_website';
        
        $form['field_camp_src']['und'][0]['value']['#attributes']['class'][] = 'urlVar';
        $form['field_camp_src']['und'][0]['value']['#attributes']['class'][] = 'utm_src';
        
        $form['field_camp_offer_txt']['und'][0]['value']['#attributes']['class'][] = 'urlVar';
        $form['field_camp_offer_txt']['und'][0]['value']['#attributes']['class'][] = 'utm_content';
        
        $form['field_camp_media']['und'][0]['value']['#attributes']['class'][] = 'urlVar';
        $form['field_camp_media']['und'][0]['value']['#attributes']['class'][] = 'utm_media';
        
        $form['field_camp_term']['und'][0]['value']['#attributes']['class'][] = 'urlVar';
        $form['field_camp_term']['und'][0]['value']['#attributes']['class'][] = 'utm_term';
        
        
        
        $form['field_gen_url']['und']['#prefix'] .= '<a href="Javascript:void(0);" class="gen_url_link">Generate url</a>';
        $form['field_gen_url']['und'][0]['value']['#attributes']['class'][] = 'genUrl';
        //debug($form['field_gen_url']['und'][0]['value']['#attributes']);
    }
}

function nexersys_landing_preprocess_page(&$vars){

    if((arg(0) == 'node' && arg(1) == 'add' && arg(2) == 'campaign') || (arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == 'edit')){
            drupal_add_js(drupal_get_path('module', 'nexersys_landing') . '/js/campaign_gen_url.js');

    }
}

function campaign_landing_form($form, &$form_state, $vars){
    
    //debug($vars);
    $form['#prefix'] = '<div id="nex_request">    <div class="left">
        <div class="left-top">
            <div><img src="/sites/all/themes/nexersystv/form/img/nex-bro-home.png"/></div>
        </div>
        <div class="left-bottom">
            <div><img src="/sites/all/themes/nexersystv/form/img/nex-form-bot-left.png"/></div>
        </div>
    </div>
    <div class="right">';
    $form['#method'] = 'post';
    //$form['#action'] = 'https://crm.zoho.com/crm/WebToLeadForm';
    $form['table_begin'] = array(
    '#markup' => t('<table id ="nexersys-form-fields">'),
    );
    $form['LEADCF13'] = array(
        '#type' => 'hidden',
        '#value' => $vars['camp_name'],
    );
    $form['LEADCF14'] = array(
        '#type' => 'hidden',
        '#value' => $vars['camp_form_url'],
    );
    $form['LEADCF1'] = array(
        '#type' => 'hidden',
        '#value' => $vars['camp_name'],
    );
    $form['LEADCF5'] = array(
        '#type' => 'hidden',
        '#value' => $vars['camp_form_url'],
    );
    $form['FirstName'] = array(
        '#prefix' => t('<tr><td class="label">First Name*</td><td>'),
        '#type' => 'textfield',
        '#title' => 'First Name',
        //'#required' => true,
        '#attributes' => array('class' => array('nexersys validate[required]'),),
        '#title_display' => 'invisible',
        '#suffix' => t('</td></tr>'),
    );
    $form['LastName'] = array(
        '#prefix' => t('<tr><td class="label">Last Name*</td><td>'),
        '#type' => 'textfield',
        '#title' => 'Last Name',
        //'#required' => true,
        '#attributes' => array('class' => array('nexersys validate[required]'),),
        '#title_display' => 'invisible',
        '#suffix' => t('</td></tr>'),
    );
    $camp_types = _camp_types();
    $clean_camp_types = $camp_types;
    array_shift($clean_camp_types);
    if($camp_types[$vars['camp_type']] == 'commercial'){
            $form['LEADCF24'] = array(
            '#prefix' => t('<tr><td class="label">Company Name*</td><td>'),
            '#type' => 'textfield',
            '#title' => 'Company Name',
            //'#required' => true,
            '#attributes' => array('class' => array('nexersys validate[required]'),),
            '#title_display' => 'invisible',
            '#suffix' => t('</td></tr>'),
        );
        $form['LEADCF3'] = array('#type' => 'hidden', '#default_value' => $camp_types[$vars['camp_type']]);

    }elseif($camp_types[$vars['camp_type']] == 'home'){
                $form['LEADCF3'] = array('#type' => 'hidden', '#default_value' => $camp_types[$vars['camp_type']]);

    }elseif($camp_types[$vars['camp_type']] == 'pro'){
        $form['LEADCF3'] = array('#type' => 'hidden', '#default_value' => $camp_types[$vars['camp_type']]);
    }else{
        //visitor has to choose, make it a select form.
        $form['LEADCF3'] = array(
        '#prefix' => t('<tr><td class="label">Model Type*</td><td>'),
        '#type' => 'select',
        '#options' => $clean_camp_types,
        '#title' => 'Model Type',
        //'#required' => true,
        '#attributes' => array('class' => array('nexersys validate[required]'),),
        '#title_display' => 'invisible',
        '#suffix' => t('</td></tr>'),
    );
    }
    $form['Phone'] = array(
        '#prefix' => t('<tr><td class="label">Phone Number*</td><td>'),
        '#type' => 'textfield',
        '#title' => 'Phone Number',
        //'#required' => true,
        '#attributes' => array('class' => array('nexersys validate[required]'),),
        '#title_display' => 'invisible',
        '#suffix' => t('</td></tr>'),
    );
        $form['Email'] = array(
        '#prefix' => t('<tr><td class="label">eMail Address*</td><td>'),
        '#type' => 'textfield',
        '#title' => 'Email Address',
        //'#required' => true,
        '#attributes' => array('class' => array('nexersys validate[required,custom[email]]'),),
        '#title_display' => 'invisible',
        '#suffix' => t('</td></tr>'),
    );
        $form['ZipCode'] = array(
        '#prefix' => t('<tr><td class="label">Zip Code*</td><td>'),
        '#type' => 'textfield',
        '#title' => 'Zip Code',
        //'#required' => true,
        '#attributes' => array('class' => array('nexersys validate[required]'),),
        '#title_display' => 'invisible',
        '#suffix' => t('</td></tr>'),
    );
        $form['LEADCF11'] = array(
        '#prefix' => t("<tr><td class='label'>I'm Located in the*</td><td>"),
        '#type' => 'select',
        '#options' => get_country_options(),
        '#title' => 'Model Type',
        //'#required' => true,
        '#attributes' => array('class' => array('nexersys validate[required]'),),
        '#title_display' => 'invisible',
        '#suffix' => t('</td></tr>'),
    );
        $form['LEADCF28'] = array(
        '#prefix' => t('<tr><td class="label">Questions</td><td>'),
        '#type' => 'textarea',
        '#title' => 'Questions',
        //'#required' => false,
        '#attributes' => array('class' => array('nexersys'),),
        '#title_display' => 'invisible',
        '#resizable' => FALSE,
        '#suffix' => t('</td></tr>'),
    );
    $form['submit'] = array(
        '#prefix' => t('<tr><td></td><td colspan="2">'),
        '#type' => 'image_button',
        '#src' => drupal_get_path('module', 'nexersys_landing') . '/img/request-but-up.png',
        '#suffix' => t('</td></tr>'),
    );
    $form['#suffix'] = '</table></div></div>';
    return $form;
}
function get_country_options(){
    return array(
  'United States' => 'United States',
  'United Kingdom' => 'United Kingdom',
  'Afghanistan' => 'Afghanistan',
  'Aland Islands' => 'Aland Islands',
  'Albania' => 'Albania',
  'Algeria' => 'Algeria',
  'American Samoa' => 'American Samoa',
  'Andorra' => 'Andorra',
  'Angola' => 'Angola',
  'Anguilla' => 'Anguilla',
  'Antarctica' => 'Antarctica',
  'Antigua & Barbuda' => 'Antigua & Barbuda',
  'Argentina' => 'Argentina',
  'Armenia' => 'Armenia',
  'Aruba' => 'Aruba',
  'Australia' => 'Australia',
  'Austria' => 'Austria',
  'Azerbaijan' => 'Azerbaijan',
  'Bahamas' => 'Bahamas',
  'Bahrain' => 'Bahrain',
  'Bangladesh' => 'Bangladesh',
  'Barbados' => 'Barbados',
  'Belarus' => 'Belarus',
  'Belgium' => 'Belgium',
  'Belize' => 'Belize',
  'Benin' => 'Benin',
  'Bermuda' => 'Bermuda',
  'Bhutan' => 'Bhutan',
  'Bolivia' => 'Bolivia',
  'Bosnia & Herzegovina' => 'Bosnia & Herzegovina',
  'Botswana' => 'Botswana',
  'Bouvet Island' => 'Bouvet Island',
  'Brazil' => 'Brazil',
  'British IOT' => 'British IOT',
  'Brunei Darussalam' => 'Brunei Darussalam',
  'Bulgaria' => 'Bulgaria',
  'Burkina Faso' => 'Burkina Faso',
  'Burundi' => 'Burundi',
  'Cambodia' => 'Cambodia',
  'Cameroon' => 'Cameroon',
  'Canada' => 'Canada',
  'Cape Verde' => 'Cape Verde',
  'Cayman Islands' => 'Cayman Islands',
  'Central African Republic' => 'Central African Republic',
  'Chad' => 'Chad',
  'Chile' => 'Chile',
  'China' => 'China',
  'Christmas Island' => 'Christmas Island',
  'Cocos (Keeling) Islands' => 'Cocos (Keeling) Islands',
  'Colombia' => 'Colombia',
  'Comoros' => 'Comoros',
  'Congo' => 'Congo',
  'The DR of' => 'The DR of',
  'Cook Islands' => 'Cook Islands',
  'Costa Rica' => 'Costa Rica',
  'Croatia' => 'Croatia',
  'Cuba' => 'Cuba',
  'Cyprus' => 'Cyprus',
  'Czech Republic' => 'Czech Republic',
  'Denmark' => 'Denmark',
  'Djibouti' => 'Djibouti',
  'Dominica' => 'Dominica',
  'Dominican Republic' => 'Dominican Republic',
  'Ecuador' => 'Ecuador',
  'Egypt' => 'Egypt',
  'El Salvador' => 'El Salvador',
  'Equatorial Guinea' => 'Equatorial Guinea',
  'Eritrea' => 'Eritrea',
  'Estonia' => 'Estonia',
  'Ethiopia' => 'Ethiopia',
  'Falkland Islands (Malvinas)' => 'Falkland Islands (Malvinas)',
  'Faroe Islands' => 'Faroe Islands',
  'Fiji' => 'Fiji',
  'Finland' => 'Finland',
  'France' => 'France',
  'French Guiana' => 'French Guiana',
  'French Polynesia' => 'French Polynesia',
  'French Southern Territories' => 'French Southern Territories',
  'Gabon' => 'Gabon',
  'Gambia' => 'Gambia',
  'Georgia' => 'Georgia',
  'Germany' => 'Germany',
  'Ghana' => 'Ghana',
  'Gibraltar' => 'Gibraltar',
  'Greece' => 'Greece',
  'Greenland' => 'Greenland',
  'Grenada' => 'Grenada',
  'Guadeloupe' => 'Guadeloupe',
  'Guam' => 'Guam',
  'Guatemala' => 'Guatemala',
  'Guinea' => 'Guinea',
  'Guinea-Bissau' => 'Guinea-Bissau',
  'Guyana' => 'Guyana',
  'Haiti' => 'Haiti',
  'Heard & Mcdonald Islands' => 'Heard & Mcdonald Islands',
  'Honduras' => 'Honduras',
  'Hong Kong' => 'Hong Kong',
  'Hungary' => 'Hungary',
  'Iceland' => 'Iceland',
  'India' => 'India',
  'Indonesia' => 'Indonesia',
  'Iran' => 'Iran',
  'Iraq' => 'Iraq',
  'Ireland' => 'Ireland',
  'Israel' => 'Israel',
  'Italy' => 'Italy',
  'Jamaica' => 'Jamaica',
  'Japan' => 'Japan',
  'Jordan' => 'Jordan',
  'Kazakhstan' => 'Kazakhstan',
  'Kenya' => 'Kenya',
  'Kiribati' => 'Kiribati',
  'Korea' => 'Korea',
  'DPR of' => 'DPR of',
  'Kuwait' => 'Kuwait',
  'Kyrgyzstan' => 'Kyrgyzstan',
  'Lao PDR' => 'Lao PDR',
  'Latvia' => 'Latvia',
  'Lebanon' => 'Lebanon',
  'Lesotho' => 'Lesotho',
  'Liberia' => 'Liberia',
  'Libyan Arab Jamahiriya' => 'Libyan Arab Jamahiriya',
  'Liechtenstein' => 'Liechtenstein',
  'Lithuania' => 'Lithuania',
  'Luxembourg' => 'Luxembourg',
  'Macao' => 'Macao',
  'Macedonia' => 'Macedonia',
  'Madagascar' => 'Madagascar',
  'Malawi' => 'Malawi',
  'Malaysia' => 'Malaysia',
  'Maldives' => 'Maldives',
  'Mali' => 'Mali',
  'Malta' => 'Malta',
  'Marshall Islands' => 'Marshall Islands',
  'Martinique' => 'Martinique',
  'Mauritania' => 'Mauritania',
  'Mauritius' => 'Mauritius',
  'Mayotte' => 'Mayotte',
  'Mexico' => 'Mexico',
  'Micronesia' => 'Micronesia',
  'Moldova' => 'Moldova',
  'Monaco' => 'Monaco',
  'Mongolia' => 'Mongolia',
  'Montserrat' => 'Montserrat',
  'Morocco' => 'Morocco',
  'Mozambique' => 'Mozambique',
  'Myanmar' => 'Myanmar',
  'Namibia' => 'Namibia',
  'Nauru' => 'Nauru',
  'Nepal' => 'Nepal',
  'Netherlands' => 'Netherlands',
  'Netherlands Antilles' => 'Netherlands Antilles',
  'New Caledonia' => 'New Caledonia',
  'New Zealand' => 'New Zealand',
  'Nicaragua' => 'Nicaragua',
  'Niger' => 'Niger',
  'Nigeria' => 'Nigeria',
  'Niue' => 'Niue',
  'Norfolk Island' => 'Norfolk Island',
  'Northern Mariana Islands' => 'Northern Mariana Islands',
  'Norway' => 'Norway',
  'Oman' => 'Oman',
  'Pakistan' => 'Pakistan',
  'Palau' => 'Palau',
  'Palestinian Territory' => 'Palestinian Territory',
  'Panama' => 'Panama',
  'Papua New Guinea' => 'Papua New Guinea',
  'Paraguay' => 'Paraguay',
  'Peru' => 'Peru',
  'Philippines' => 'Philippines',
  'Pitcairn' => 'Pitcairn',
  'Poland' => 'Poland',
  'Portugal' => 'Portugal',
  'Puerto Rico' => 'Puerto Rico',
  'Qatar' => 'Qatar',
  'Réunion' => 'Réunion',
  'Romania' => 'Romania',
  'Russian Federation' => 'Russian Federation',
  'Rwanda' => 'Rwanda',
  'Saint Helena' => 'Saint Helena',
  'Saint Kitts & Nevis' => 'Saint Kitts & Nevis',
  'Saint Lucia' => 'Saint Lucia',
  'Saint Pierre & Miquelon' => 'Saint Pierre & Miquelon',
  'Saint Vincent & The Grenadines' => 'Saint Vincent & The Grenadines',
  'Samoa' => 'Samoa',
  'San Marino' => 'San Marino',
  'Sao Tome & Principe' => 'Sao Tome & Principe',
  'Saudi Arabia' => 'Saudi Arabia',
  'Scotland' => 'Scotland',
  'Senegal' => 'Senegal',
  'Serbia & Montenegro' => 'Serbia & Montenegro',
  'Seychelles' => 'Seychelles',
  'Sierra Leone' => 'Sierra Leone',
  'Singapore' => 'Singapore',
  'Slovakia' => 'Slovakia',
  'Slovenia' => 'Slovenia',
  'Solomon Islands' => 'Solomon Islands',
  'Somalia' => 'Somalia',
  'South Africa' => 'South Africa',
  'South Georgia & The SSI' => 'South Georgia & The SSI',
  'Spain' => 'Spain',
  'Sri Lanka' => 'Sri Lanka',
  'Sudan' => 'Sudan',
  'Suriname' => 'Suriname',
  'Svalbard & Jan Mayen' => 'Svalbard & Jan Mayen',
  'Swaziland' => 'Swaziland',
  'Sweden' => 'Sweden',
  'Switzerland' => 'Switzerland',
  'Syrian Arab Republic' => 'Syrian Arab Republic',
  'Taiwan' => 'Taiwan',
  'Tajikistan' => 'Tajikistan',
  'Tanzania' => 'Tanzania',
  'Thailand' => 'Thailand',
  'Timor-Leste' => 'Timor-Leste',
  'Togo' => 'Togo',
  'Tokelau' => 'Tokelau',
  'Tonga' => 'Tonga',
  'Trinidad & Tobago' => 'Trinidad & Tobago',
  'Tunisia' => 'Tunisia',
  'Turkey' => 'Turkey',
  'Turkmenistan' => 'Turkmenistan',
  'Turks & Caicos Islands' => 'Turks & Caicos Islands',
  'Tuvalu' => 'Tuvalu',
  'Uganda' => 'Uganda',
  'Ukraine' => 'Ukraine',
  'United Arab Emirates' => 'United Arab Emirates',
  'Uruguay' => 'Uruguay',
  'Uzbekistan' => 'Uzbekistan',
  'Vanuatu' => 'Vanuatu',
  'Vatican City State' => 'Vatican City State',
  'Venezuela' => 'Venezuela',
  'Vietnam' => 'Vietnam',
  'Virgin Islands' => 'Virgin Islands',
  'British' => 'British',
  'U.S.' => 'U.S.',
  'Wallis & Futuna' => 'Wallis & Futuna',
  'Western Sahara' => 'Western Sahara',
  'Yemen' => 'Yemen',
  'Zambia' => 'Zambia',
  'Zimbabwe' => 'Zimbabwe',
    );
}
function campaign_landing_form_submit($form, &$form_state){
    //debug($form_state['values']);
}